# Generated by Django 3.1.7 on 2021-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210419_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='city', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Ghorashal', 'Ghorashal'), ('Monohardi', 'Monohardi'), ('Shibpur', 'Shibpur'), ('Raipura', 'Raipura'), ('Madhabdi', 'Madhabdi'), ('Mirzapur', 'Mirzapur'), ('Dhanbari', 'Dhanbari'), ('Madhupur', 'Madhupur'), ('Chhagalnaiya', 'Chhagalnaiya'), ('Parshuram', 'Parshuram'), ('Bandarban', 'Bandarban'), ('Rangamati', 'Rangamati')], default='state', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(default='zipcode'),
        ),
    ]
