# Generated by Django 3.1.7 on 2021-04-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210419_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Dhaka', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Bangla', 'Bangla')], default='English', max_length=7),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='root', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Ghorashal', 'Ghorashal'), ('Monohardi', 'Monohardi'), ('Shibpur', 'Shibpur'), ('Raipura', 'Raipura'), ('Madhabdi', 'Madhabdi'), ('Mirzapur', 'Mirzapur'), ('Dhanbari', 'Dhanbari'), ('Madhupur', 'Madhupur'), ('Chhagalnaiya', 'Chhagalnaiya'), ('Parshuram', 'Parshuram'), ('Bandarban', 'Bandarban'), ('Rangamati', 'Rangamati')], default='Dhaka', max_length=50),
        ),
    ]
